// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEutlZoI6SeIhI7R8hFHgkiukkdVuQkUk',
    appId: '1:344444161331:web:69d70faf4a361ba5914246',
    messagingSenderId: '344444161331',
    projectId: 'medialertai-101be',
    authDomain: 'medialertai-101be.firebaseapp.com',
    storageBucket: 'medialertai-101be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcJ7JtUwMi2fpdQ8l0tc9fCtvyE32EqPE',
    appId: '1:344444161331:android:d453959bf5c4492f914246',
    messagingSenderId: '344444161331',
    projectId: 'medialertai-101be',
    storageBucket: 'medialertai-101be.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQB4nZ1IBWkvyNxc-hiICX2yvUpbWhdEU',
    appId: '1:344444161331:ios:3a69f55001be6245914246',
    messagingSenderId: '344444161331',
    projectId: 'medialertai-101be',
    storageBucket: 'medialertai-101be.firebasestorage.app',
    iosBundleId: 'com.example.medialertAi',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQB4nZ1IBWkvyNxc-hiICX2yvUpbWhdEU',
    appId: '1:344444161331:ios:3a69f55001be6245914246',
    messagingSenderId: '344444161331',
    projectId: 'medialertai-101be',
    storageBucket: 'medialertai-101be.firebasestorage.app',
    iosBundleId: 'com.example.medialertAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEutlZoI6SeIhI7R8hFHgkiukkdVuQkUk',
    appId: '1:344444161331:web:222e81d72e4eb2f6914246',
    messagingSenderId: '344444161331',
    projectId: 'medialertai-101be',
    authDomain: 'medialertai-101be.firebaseapp.com',
    storageBucket: 'medialertai-101be.firebasestorage.app',
  );
}
